# Generated by Django 5.2.4 on 2025-08-18 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BikeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bike_model', models.CharField(choices=[('honda-cb-shine', 'Honda CB Shine'), ('hero-splendor', 'Hero Splendor Plus'), ('bajaj-pulsar-150', 'Bajaj Pulsar 150'), ('tvs-apache', 'TVS Apache RTR 160'), ('yamaha-fz', 'Yamaha FZ-S'), ('re-classic', 'Royal Enfield Classic 350'), ('ktm-duke', 'KTM Duke 200'), ('suzuki-gixxer', 'Suzuki Gixxer'), ('other', 'Other')], max_length=50)),
                ('bike_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('service_type', models.CharField(choices=[('basic', 'Basic Service'), ('standard', 'Standard Service'), ('premium', 'Premium Service'), ('oil-change', 'Oil Change'), ('brake-service', 'Brake Service'), ('chain-cleaning', 'Chain Cleaning'), ('tire-replacement', 'Tire Replacement'), ('engine-tuning', 'Engine Tuning'), ('electrical-check', 'Electrical System Check'), ('carburetor-cleaning', 'Carburetor Cleaning')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=50)),
                ('doorstep_service', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('technician_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('service_start_time', models.DateTimeField(blank=True, null=True)),
                ('service_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoorstepService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_type', models.CharField(choices=[('breakdown', 'Breakdown Service'), ('maintenance', 'Regular Maintenance'), ('oil-change', 'Oil Change'), ('tire-repair', 'Tire Repair'), ('battery', 'Battery Service'), ('brake-adjustment', 'Brake Adjustment'), ('chain-service', 'Chain Service'), ('full-service', 'Complete Service')], max_length=50)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('time_slot', models.CharField(choices=[('8:00 AM - 10:00 AM', '8:00 AM - 10:00 AM'), ('10:00 AM - 12:00 PM', '10:00 AM - 12:00 PM'), ('12:00 PM - 2:00 PM', '12:00 PM - 2:00 PM'), ('2:00 PM - 4:00 PM', '2:00 PM - 4:00 PM'), ('4:00 PM - 6:00 PM', '4:00 PM - 6:00 PM'), ('6:00 PM - 8:00 PM', '6:00 PM - 8:00 PM')], max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_service', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('technician_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('technician_assigned', 'Technician Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service_start_time', models.DateTimeField(blank=True, null=True)),
                ('service_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doorstep_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('doorstep_service', models.BooleanField(default=False)),
                ('urgent_service', models.BooleanField(default=False)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('km_run', models.IntegerField()),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('has_accidents', models.BooleanField(default=False)),
                ('modifications', models.BooleanField(default=False)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resell_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
