# Generated by Django 5.2.4 on 2025-08-19 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(choices=[('honda-cb-shine', 'Honda CB Shine'), ('hero-splendor', 'Hero Splendor Plus'), ('bajaj-pulsar-150', 'Bajaj Pulsar 150'), ('tvs-apache', 'TVS Apache RTR 160'), ('yamaha-fz', 'Yamaha FZ-S'), ('re-classic', 'Royal Enfield Classic 350'), ('ktm-duke', 'KTM Duke 200'), ('suzuki-gixxer', 'Suzuki Gixxer'), ('honda-activa', 'Honda Activa'), ('tvs-jupiter', 'TVS Jupiter'), ('bajaj-avenger', 'Bajaj Avenger'), ('yamaha-r15', 'Yamaha R15'), ('other', 'Other')], max_length=50)),
                ('custom_model_name', models.CharField(blank=True, help_text="Custom name if 'Other' is selected", max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('engine_capacity', models.IntegerField(blank=True, help_text='Engine capacity in CC', null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('km_run', models.IntegerField(default=0, help_text='Total kilometers run')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary vehicle for the user')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('user', 'registration_number')},
        ),
        migrations.AddField(
            model_name='bikeservice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='doorstepservice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doorstep_services', to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='resellvalue',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resell_estimates', to='api.vehicle'),
        ),
    ]
