# Generated by Django 4.2.7 on 2026-04-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_userprofile_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeservice',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='bike_registration',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='service_end_time',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='service_start_time',
        ),
        migrations.RemoveField(
            model_name='bikeservice',
            name='technician_assigned',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='service_end_time',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='service_start_time',
        ),
        migrations.RemoveField(
            model_name='doorstepservice',
            name='technician_assigned',
        ),
    ]
